version: "3.8"

services:
  synthr_db:
    image: postgres:16
    container_name: synthr_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-synthr_db}
    ports:
      - "5436:5432"
    volumes:
      - synthr_postgres_data:/var/lib/postgresql/data
    networks:
      - synthr_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  synthr_network:
    driver: bridge

volumes:
  synthr_postgres_data:
